version: '3.8'

services:
  ocdb:
    image: postgres:9.5
    container_name: ocdb
    environment:
      POSTGRES_INITDB_ARGS: "-E 'UTF-8' --locale=POSIX"
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - ocdb-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  oc:
    image: piegsaj/openclinica:oc-3.13
    container_name: oc
    hostname: oc
    environment:
      LOG_LEVEL: INFO
      TZ: UTC-1
      DB_TYPE: postgres
      DB_HOST: ocdb
      DB_NAME: openclinica
      DB_USER: clinica
      DB_PASS: clinica
      DB_PORT: 5432
      SUPPORT_URL: "https://www.openclinica.com/community-edition-open-source-edc/"
    ports:
      - "80:8080"
    depends_on:
      - ocdb
    volumes:
      - oc-data:/usr/local/tomcat/openclinica.data

volumes:
  ocdb-data:
  oc-data:
